<Project>
  <!--
    Directory.Packages.props enables Central Package Management.

    This means NuGet package versions can be managed centrally here instead
    of being repeated in every project file.

    Later we will add package versions for:
      - JWT bearer authentication
      - Swagger/OpenAPI
      - Refit
      - Refit.HttpClientFactory
      - Unit testing packages
  -->
  <PropertyGroup>
    <!--
      Enables Central Package Management for all projects under this directory.
    -->
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <!--
      PackageVersion entries will be added in later implementation steps.
    -->
  </ItemGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
    <!--<PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />-->
    <!--<PackageVersion Include="Microsoft.OpenApi" Version="3.9.0" />-->
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="10.2.3" />
    <PackageVersion Include="Swashbuckle.AspNetCore.Annotations" Version="10.2.3" />
    <PackageVersion Include="Refit" Version="13.1.0" />
    <PackageVersion Include="Refit.HttpClientFactory" Version="13.1.0" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.10" />
    <PackageVersion Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.10" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.10" />
    <PackageVersion Include="Microsoft.IdentityModel.Tokens" Version="8.21.0" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.10" />



  </ItemGroup>
</Project>