using ListMaker.Contracts.Lists;

namespace ListMaker.Api.Features.Lists;

/// <summary>
/// Provides a stable, reproducible list of generated people.
/// </summary>
/// <remarks>
/// This provider intentionally uses a fixed random seed, so the generated
/// people remain the same across application runs. This is useful for API
/// integration demos, repeatable tests, and stable Postman assertions.
/// </remarks>
public sealed class StablePersonListProvider : IPersonListProvider
    {
    /// <summary>
    /// The number of person records generated by the provider.
    /// </summary>
    private const int PersonCount = 50;

    /// <summary>
    /// Fixed seed used to make random generation deterministic.
    /// </summary>
    private const int RandomSeed = 20260721;

    /// <summary>
    /// Minimum generated age.
    /// </summary>
    private const int MinimumAge = 18;

    /// <summary>
    /// Maximum generated age.
    /// </summary>
    private const int MaximumAge = 65;

    /// <summary>
    /// Stable first-name source values.
    /// </summary>
    private static readonly string[] Names =
    [
        "Arman",
        "Sara",
        "Nima",
        "Mina",
        "Kian",
        "Leila",
        "Reza",
        "Tara",
        "Omid",
        "Neda",
        "Sina",
        "Yasmin",
        "Amir",
        "Shirin",
        "Pouya",
        "Roya",
        "Navid",
        "Darya",
        "Farhad",
        "Elham"
    ];

    /// <summary>
    /// Stable family-name source values.
    /// </summary>
    private static readonly string[] Families =
    [
        "Ahmadi",
        "Karimi",
        "Hosseini",
        "Moradi",
        "Rahimi",
        "Ebrahimi",
        "Mohammadi",
        "Kazemi",
        "Jafari",
        "Rostami",
        "Sadeghi",
        "Akbari",
        "Ghasemi",
        "Najafi",
        "Zamani",
        "Fallahi",
        "Asadi",
        "Mousavi",
        "Salehi",
        "Yazdani"
    ];

    /// <summary>
    /// Stable gender source values.
    /// </summary>
    private static readonly string[] Genders =
    [
        "Male",
        "Female",
        "non-Binary"
    ];

    /// <summary>
    /// Cached generated people.
    /// </summary>
    private readonly IReadOnlyList<PersonListItemDto> _generatedPeople;

    /// <summary>
    /// Initializes a new instance of the <see cref="StablePersonListProvider"/> class.
    /// </summary>
    public StablePersonListProvider ()
        {
        _generatedPeople = GeneratePeople();
        }

    /// <inheritdoc />
    public IReadOnlyList<PersonListItemDto> GetGeneratedPeople ()
        {
        return _generatedPeople;
        }

    /// <summary>
    /// Generates the stable list of people using the fixed random seed.
    /// </summary>
    /// <returns>
    /// A stable read-only list of generated person records.
    /// </returns>
    private static IReadOnlyList<PersonListItemDto> GeneratePeople ()
        {
        var random = new Random(RandomSeed);
        var people = new List<PersonListItemDto>(capacity: PersonCount);

        for (int index = 1; index <= PersonCount; index++)
            {
            string name = Names[random.Next(Names.Length)];
            string family = Families[random.Next(Families.Length)];
            int age = random.Next(MinimumAge, MaximumAge + 1);
            string gender = Genders[random.Next(Genders.Length)];

            people.Add(new PersonListItemDto
                {
                Id = index,
                Name = name,
                Family = family,
                Age = age,
                Gender = gender
                });
            }

        return people;
        }
    }
